export const EARTH_DAY = 2000

export const EARTH_YEAR = 10 * EARTH_DAY
// export const EARTH_YEAR = 360 * EARTH_DAY

/**
 * ALL DISTANCES IN AU UNIT
 */

const EARTH_SEMI_MAJOR_AXIS = 1
const EARTH_RADIUS = 6371

const VENUS_AXIAL_TILT = 2.6
const VENUS_RADIUS = 6000

const MERCURY_AXIAL_TILT = 0
const MERCURY_INCLINATION = 7
const MERCURY_RADIUS = 2440

const MARS_AXIAL_TILT = 25
const MARS_INCLINATION = 2
const MARS_RADIUS = 3390

const JUPITER_SEMI_MAJOR_AXIS = 5.2
const JUPITER_INCLINATION = 1.3
const JUPITER_RADIUS = 69900
